added a timeout for the step waiting for the test database to be available in the e2e job

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -53,10 +53,18 @@ jobs:
 
       - name: Wait for test database to start
         run: |
-          until PGPASSWORD=${{ secrets.TEST_POSTGRES_PASSWORD }} psql -h "localhost" -U "test_user" -c '\q'; do
+          attempts=0
+          until PGPASSWORD=${{ secrets.TEST_POSTGRES_PASSWORD }} psql -h "localhost" -U "test_user" -c '\q' || [ $attempts -eq 60 ]; do
+            attempts=$((attempts+1))
             echo "Postgres is still unavailable - sleeping"
             sleep 1
           done
+
+          if [ $attempts -eq 60 ]; then
+            echo "Failed to connect to Postgres after 60 attempts, exiting"
+            exit 1
+          fi
+
           echo "Postgres is up and running"
 
       - name: Start test app
